// ARRAYS START WIYH []

//ARRAY IS USED DEFINE MULTIPLE VALUES(STRINGS,NUMBERS,BOOLEANS,ARRAY,OBJECT)
[1,2,3,4,5]
[1, 2, 3, 4, 5]
[
    1,
    2,
    3,
    4,
    5
];
['HARISH','HARSHA','MANI','BALU','CHANDU']

// ARRAY START WITH ZERO, ONE, TWO, THREE, FOURE, FIVE
//[]POSITION => VALUE
// 4TH VALUE KAVANAPUDU THREE EVVALI

